insert into category (id, name) values (null, 'Comida');
insert into category (id, name) values (null, 'Bebida');
insert into category (id, name) values (null, 'Complementos');

insert into product (id, name, price, category_id) values (null, 'Juice - Orange, Concentrate', 91, 2);
insert into product (id, name, price, category_id) values (null, 'Beef - Ground, Extra Lean, Fresh', 87, 1);
insert into product (id, name, price, category_id) values (null, 'Cheese - Parmesan Grated', 39, 1);
insert into product (id, name, price, category_id) values (null, 'Cups 10oz Trans', 67, 1);
insert into product (id, name, price, category_id) values (null, 'Wine - Beringer Founders Estate', 27, 2);
insert into product (id, name, price, category_id) values (null, 'Bread - Wheat Baguette', 82, 2);
insert into product (id, name, price, category_id) values (null, 'Quail - Eggs, Fresh', 3, 2);
insert into product (id, name, price, category_id) values (null, 'Cheese - Mascarpone', 97, 2);
insert into product (id, name, price, category_id) values (null, 'Mace', 25, 2);
insert into product (id, name, price, category_id) values (null, 'Oil - Shortening - All - Purpose', 63, 2);
insert into product (id, name, price, category_id) values (null, 'Marjoram - Fresh', 60, 2);
insert into product (id, name, price, category_id) values (null, 'Turnip - White', 74, 2);
insert into product (id, name, price, category_id) values (null, 'Pork Salted Bellies', 38, 2);
insert into product (id, name, price, category_id) values (null, 'Longos - Greek Salad', 15, 2);
insert into product (id, name, price, category_id) values (null, 'Amaretto', 85, 2);
insert into product (id, name, price, category_id) values (null, 'Godiva White Chocolate', 97, 2);
insert into product (id, name, price, category_id) values (null, 'Tomatoes - Roma', 61, 2);
insert into product (id, name, price, category_id) values (null, 'Oven Mitt - 13 Inch', 1, 3);
insert into product (id, name, price, category_id) values (null, 'Vermouth - White, Cinzano', 72, 2);
insert into product (id, name, price, category_id) values (null, 'Club Soda - Schweppes, 355 Ml', 38, 2);
insert into product (id, name, price, category_id) values (null, 'Fenngreek Seed', 1, 1);
insert into product (id, name, price, category_id) values (null, 'Dill Weed - Dry', 72, 1);
insert into product (id, name, price, category_id) values (null, 'Pepper - Green', 56, 1);
insert into product (id, name, price, category_id) values (null, 'Bacardi Breezer - Tropical', 35, 2);
insert into product (id, name, price, category_id) values (null, 'Wine - Merlot Vina Carmen', 14, 2);
insert into product (id, name, price, category_id) values (null, 'Sauce - Black Current, Dry Mix', 9, 1);
insert into product (id, name, price, category_id) values (null, 'Crab - Soft Shell', 17, 1);
insert into product (id, name, price, category_id) values (null, 'Jameson Irish Whiskey', 19, 2);
insert into product (id, name, price, category_id) values (null, 'Muffin Chocolate Individual Wrap', 77, 1);
insert into product (id, name, price, category_id) values (null, 'Mussels - Frozen', 95, 1);